name: Create new release from release branch

on:
  pull_request:
    branches: 
      - 'release**'

jobs:
  is-merge:
    if:  github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - run: echo "this PR has been merged"
  create-release:
    if:  startsWith(github.head_ref, 'releases/') && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - run: echo "A release branch has been merged with trunk, time to create a new release"
