name: Create new release from release branch

on:
  pull_request:
    types:
      - closed
jobs:
  create-release:
    if:  startsWith(github.head_ref, 'releases/') && github.event.pull_request_target.merged == true
    runs-on: ubuntu-latest
    steps:
      - run: echo "A release branch has been merged with trunk, time to create a new release"
